import type { Metadata } from "next";
import "@/styles/globals.scss";
import "@mantine/core/styles.css";
import { cookies } from "next/headers";
import { fonts } from "@/_fonts/rubik";
import { logoMiniWhite } from "@/utils/assets";
import Head from "next/head";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import NextAuthProvider from "@/_context/auth";
import { Notifications } from "@mantine/notifications";
import { AppWrapper } from "@/_context";
import { Suspense } from "react";
import { theme } from "@/theme/theme";
import "@mantine/core/styles/global.css";
import { AdminNavbar, Navbar } from "@/components/navbar/navbar";
import Loading from "./loading";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Eunit - Монголын зарын сайт",
    template: "Eunit | %s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const userRole = cookieStore.get("user-role")?.value;
  return (
    <html lang="en" className={fonts.rubik.variable}>
      {/* <html lang="en"> */}
      <Head>
        <link
          rel=" shortcut icon"
          href={logoMiniWhite}
          type="image/png"
          sizes="32x32"
        />
        <ColorSchemeScript />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </Head>
      <body>
        <MantineProvider
          theme={theme}
          defaultColorScheme="light"
          withGlobalClasses
          withStaticClasses
        >
          <NextAuthProvider>
            <Notifications />
            <AppWrapper>
              <Suspense fallback={<Loading />}>
                {userRole == "admin" ? <AdminNavbar /> : <Navbar />}
                {children}

                {/* <ScrollTop /> */}
              </Suspense>
            </AppWrapper>
          </NextAuthProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
